import Head from 'next/head'

export default function Blog() {
  return (
    <div >
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <h2> Blog </h2>
    </div>
  )
}
