import Head from 'next/head'
import styles from '../styles/Blog.module.css'


export default function Blog() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Dzhangir Bayandarov</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/leopard.ico" />
      </Head>
      <h2> This page is a work in progress... </h2>
    </div>
  )
}
