import Head from 'next/head'
import styles from '../styles/Home.module.css'

export default function Home() {
  return (
    <>
      <Head>
        <title>Dzhangir Bayandarov</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/leopard.ico" />
      </Head>
      <div className={styles.container}>
        {/* <Image src={profilePic} alt="Picture of the author" /> */}
        <h2> <strong>Hey there, I am Dzhangir.</strong></h2>
      </div>
      <div className={styles.textContainer}>
        <p className={styles.textItem}> I am a computer science student at University of California, San Diego. I am an aspiring software engineer, currently working on web development projects.</p>
        <p className={styles.textItem}> I am interested in all things technology, from AI research and data analytics to software engineering and product development.
        Outside of tech I love doing jiu-jitsu, boxing and watching UFC fights. My dream job is to work for company that uses machine learning to analyze sports to combine data analytics with my passion.</p>
        <p className={styles.textItem}> Thank you for visiting my website, I am happy to see you here.</p>
      </div>
    </>
  )
}
