import Head from 'next/head'
import styles from '../styles/Home.module.css'
import Navbar from '../components/Navbar'
import Image from 'next/image'
import profilePic from '../public/profile.jpg'

export default function Home() {
  return (
    <>
      <Head>
        <title>Personal Blog</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className={styles.container}>
      <Image src={profilePic} alt="Picture of the author" />
      <h3> <strong>Hey there, I am Dzhangir.</strong></h3>
      </div>
      <div className={styles.textContainer}>
          <p className={styles.textItem}> I am a 3rd year computer science student, residing in San Diego, CA. I am an aspiring software engineer, currently working on web development projects.</p>
          <p className={styles.textItem}><span className={styles.paragraph}>Personal:</span> I am interested in all things technology, from AI research and data analytics to software engineering and product development.</p>
          <p className={styles.textItem}> <span className={styles.paragraph}>Work:</span> I am currently seeking software engineering internships for Summer 2022. I am willing to relocate anywhere in the US.  </p>
          <p className={styles.textItem}> Thank you for visiting my website, I am happy to see you here.</p>
      </div>
    </>
  )
}
