import Head from 'next/head'
import styles from '../styles/Home.module.css'
import Navbar from '../components/Navbar'
import Image from 'next/image'
import profilePic from '../public/profile.jpg'

export default function Home() {
  return (
    <>
      <Head>
        <title>Personal Blog</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className={styles.container}>
      <Image src={profilePic} alt="Picture of the author" />
      <h4> Hey there, I am Dzhangir </h4>
      </div>
      <div className={styles.textContainer}>
          <p className={styles.textItem}> I am a Software Engineer residing in Seattle, Washington. I spend my day time developing distributed Big Data applications at Amazon Inc. and evenings tinkering with my personal ML / Web projects.</p>
          <p className={styles.textItem}><span>Personal:</span> I use product strategy and systems thinking to develop scalable, reliable, resilient, frugal and efficient applications that delights customers. I am interested in all things technology, software engineering and product and read and write about these topics. Say hi to me on Twitter or Linkedin!</p>
          <p className={styles.textItem}> <span>Work:</span> I am a Software Engineer residing in Seattle, Washington. I spend my day time developing distributed Big Data applications at Amazon Inc. and evenings tinkering with my personal ML / Web projects.</p>
          <p className={styles.textItem}> Thank you for visiting my website, I am happy to see you here.</p>
      </div>
    </>
  )
}
