import Head from 'next/head'

export default function Projects() {
  return (
    <div>
      <Head>
        <title>Dzhangir Bayandarov</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/leopard.ico" />
      </Head>

      <h2>Projects</h2>
    </div>
  )
}
