import Head from 'next/head';

const resume = () => {
    return (
        <div>
            <Head>
                <title>Personal Blog</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <h2> Resume </h2>
        </div>
    )
}

export default resume
